# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(19191B)
$foreground = rgb(FBE9CF)
$color0 = rgb(404042)
$color1 = rgb(2C5365)
$color2 = rgb(AA546B)
$color3 = rgb(917DAB)
$color4 = rgb(749AA0)
$color5 = rgb(AF8C8B)
$color6 = rgb(B78F59)
$color7 = rgb(F1D7B3)
$color8 = rgb(A9967D)
$color9 = rgb(3B6F87)
$color10 = rgb(E3708F)
$color11 = rgb(C2A6E4)
$color12 = rgb(9BCDD5)
$color13 = rgb(E9BAB9)
$color14 = rgb(F4BF77)
$color15 = rgb(F1D7B3)
