# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252526)
$foreground = rgb(ECEFDC)
$color0 = rgb(4A4B4C)
$color1 = rgb(1A1C1F)
$color2 = rgb(222425)
$color3 = rgb(494C3F)
$color4 = rgb(555943)
$color5 = rgb(707459)
$color6 = rgb(979D73)
$color7 = rgb(DCDFC4)
$color8 = rgb(9A9C89)
$color9 = rgb(23252A)
$color10 = rgb(2D3031)
$color11 = rgb(616554)
$color12 = rgb(717659)
$color13 = rgb(959B77)
$color14 = rgb(C9D19A)
$color15 = rgb(DCDFC4)
