# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 
#
# $background = rgb(1C1C1E)
# $foreground = rgb(DDD5ED)
# $color0 = rgb(424245)
# $color1 = rgb(14141D)
# $color2 = rgb(1A1924)
# $color3 = rgb(3A3D56)
# $color4 = rgb(453D5B)
# $color5 = rgb(706092)
# $color6 = rgb(766599)
# $color7 = rgb(C6BBDD)
# $color8 = rgb(8A839B)
# $color9 = rgb(1A1B26)
# $color10 = rgb(222230)
# $color11 = rgb(4E5173)
# $color12 = rgb(5C5179)
# $color13 = rgb(9580C2)
# $color14 = rgb(9E87CD)
# $color15 = rgb(C6BBDD)

$background = rgb(121212)
$foreground = rgb(CCCCCC)
$color0 = rgb(080808)
$color1 = rgb(191919)
$color2 = rgb(2A2A2A)
$color3 = rgb(444444)
$color4 = rgb(555555)
$color5 = rgb(7A7A7A)
$color6 = rgb(AAAAAA)
$color7 = rgb(CCCCCC)
$color8 = rgb(DDDDDD)
$color9 = rgb(F1F1F1)
$color10 = rgb(8CF8F7)
$color11 = rgb(66B2B2)
$color12 = rgb(A6DBFF)
$color13 = rgb(FFCAFF)
$color14 = rgb(FCE094)
$color15 = rgb(1BFD9C)
